/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as TestOrcamentoRouteImport } from './routes/test-orcamento'
import { Route as ReunioesRouteImport } from './routes/reunioes'
import { Route as OficinaRouteImport } from './routes/oficina'
import { Route as AlmoxarifadoRouteImport } from './routes/almoxarifado'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperadorIdRouteImport } from './routes/operador.$id'
import { Route as ApiPublicHooksWeeklyMissingPartsRouteImport } from './routes/api/public/hooks/weekly-missing-parts'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const TestOrcamentoRoute = TestOrcamentoRouteImport.update({
  id: '/test-orcamento',
  path: '/test-orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ReunioesRoute = ReunioesRouteImport.update({
  id: '/reunioes',
  path: '/reunioes',
  getParentRoute: () => rootRouteImport,
} as any)
const OficinaRoute = OficinaRouteImport.update({
  id: '/oficina',
  path: '/oficina',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmoxarifadoRoute = AlmoxarifadoRouteImport.update({
  id: '/almoxarifado',
  path: '/almoxarifado',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorIdRoute = OperadorIdRouteImport.update({
  id: '/operador/$id',
  path: '/operador/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksWeeklyMissingPartsRoute =
  ApiPublicHooksWeeklyMissingPartsRouteImport.update({
    id: '/api/public/hooks/weekly-missing-parts',
    path: '/api/public/hooks/weekly-missing-parts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/almoxarifado': typeof AlmoxarifadoRoute
  '/oficina': typeof OficinaRoute
  '/reunioes': typeof ReunioesRoute
  '/test-orcamento': typeof TestOrcamentoRoute
  '/vendas': typeof VendasRoute
  '/operador/$id': typeof OperadorIdRoute
  '/api/public/hooks/weekly-missing-parts': typeof ApiPublicHooksWeeklyMissingPartsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/almoxarifado': typeof AlmoxarifadoRoute
  '/oficina': typeof OficinaRoute
  '/reunioes': typeof ReunioesRoute
  '/test-orcamento': typeof TestOrcamentoRoute
  '/vendas': typeof VendasRoute
  '/operador/$id': typeof OperadorIdRoute
  '/api/public/hooks/weekly-missing-parts': typeof ApiPublicHooksWeeklyMissingPartsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/almoxarifado': typeof AlmoxarifadoRoute
  '/oficina': typeof OficinaRoute
  '/reunioes': typeof ReunioesRoute
  '/test-orcamento': typeof TestOrcamentoRoute
  '/vendas': typeof VendasRoute
  '/operador/$id': typeof OperadorIdRoute
  '/api/public/hooks/weekly-missing-parts': typeof ApiPublicHooksWeeklyMissingPartsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/almoxarifado'
    | '/oficina'
    | '/reunioes'
    | '/test-orcamento'
    | '/vendas'
    | '/operador/$id'
    | '/api/public/hooks/weekly-missing-parts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/almoxarifado'
    | '/oficina'
    | '/reunioes'
    | '/test-orcamento'
    | '/vendas'
    | '/operador/$id'
    | '/api/public/hooks/weekly-missing-parts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/almoxarifado'
    | '/oficina'
    | '/reunioes'
    | '/test-orcamento'
    | '/vendas'
    | '/operador/$id'
    | '/api/public/hooks/weekly-missing-parts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlmoxarifadoRoute: typeof AlmoxarifadoRoute
  OficinaRoute: typeof OficinaRoute
  ReunioesRoute: typeof ReunioesRoute
  TestOrcamentoRoute: typeof TestOrcamentoRoute
  VendasRoute: typeof VendasRoute
  OperadorIdRoute: typeof OperadorIdRoute
  ApiPublicHooksWeeklyMissingPartsRoute: typeof ApiPublicHooksWeeklyMissingPartsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-orcamento': {
      id: '/test-orcamento'
      path: '/test-orcamento'
      fullPath: '/test-orcamento'
      preLoaderRoute: typeof TestOrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reunioes': {
      id: '/reunioes'
      path: '/reunioes'
      fullPath: '/reunioes'
      preLoaderRoute: typeof ReunioesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oficina': {
      id: '/oficina'
      path: '/oficina'
      fullPath: '/oficina'
      preLoaderRoute: typeof OficinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almoxarifado': {
      id: '/almoxarifado'
      path: '/almoxarifado'
      fullPath: '/almoxarifado'
      preLoaderRoute: typeof AlmoxarifadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/$id': {
      id: '/operador/$id'
      path: '/operador/$id'
      fullPath: '/operador/$id'
      preLoaderRoute: typeof OperadorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-missing-parts': {
      id: '/api/public/hooks/weekly-missing-parts'
      path: '/api/public/hooks/weekly-missing-parts'
      fullPath: '/api/public/hooks/weekly-missing-parts'
      preLoaderRoute: typeof ApiPublicHooksWeeklyMissingPartsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlmoxarifadoRoute: AlmoxarifadoRoute,
  OficinaRoute: OficinaRoute,
  ReunioesRoute: ReunioesRoute,
  TestOrcamentoRoute: TestOrcamentoRoute,
  VendasRoute: VendasRoute,
  OperadorIdRoute: OperadorIdRoute,
  ApiPublicHooksWeeklyMissingPartsRoute: ApiPublicHooksWeeklyMissingPartsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
