/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OficinaRouteImport } from './routes/oficina'
import { Route as AlmoxarifadoRouteImport } from './routes/almoxarifado'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperadorIdRouteImport } from './routes/operador.$id'

const OficinaRoute = OficinaRouteImport.update({
  id: '/oficina',
  path: '/oficina',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmoxarifadoRoute = AlmoxarifadoRouteImport.update({
  id: '/almoxarifado',
  path: '/almoxarifado',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorIdRoute = OperadorIdRouteImport.update({
  id: '/operador/$id',
  path: '/operador/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/almoxarifado': typeof AlmoxarifadoRoute
  '/oficina': typeof OficinaRoute
  '/operador/$id': typeof OperadorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/almoxarifado': typeof AlmoxarifadoRoute
  '/oficina': typeof OficinaRoute
  '/operador/$id': typeof OperadorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/almoxarifado': typeof AlmoxarifadoRoute
  '/oficina': typeof OficinaRoute
  '/operador/$id': typeof OperadorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/almoxarifado' | '/oficina' | '/operador/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/almoxarifado' | '/oficina' | '/operador/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/almoxarifado'
    | '/oficina'
    | '/operador/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlmoxarifadoRoute: typeof AlmoxarifadoRoute
  OficinaRoute: typeof OficinaRoute
  OperadorIdRoute: typeof OperadorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/oficina': {
      id: '/oficina'
      path: '/oficina'
      fullPath: '/oficina'
      preLoaderRoute: typeof OficinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almoxarifado': {
      id: '/almoxarifado'
      path: '/almoxarifado'
      fullPath: '/almoxarifado'
      preLoaderRoute: typeof AlmoxarifadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/$id': {
      id: '/operador/$id'
      path: '/operador/$id'
      fullPath: '/operador/$id'
      preLoaderRoute: typeof OperadorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlmoxarifadoRoute: AlmoxarifadoRoute,
  OficinaRoute: OficinaRoute,
  OperadorIdRoute: OperadorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
